global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Métriques système de la machine hôte
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']

  # Métriques des containers Docker
  - job_name: cadvisor
    static_configs:
      - targets: ['localhost:8080']

  # Métriques du pipeline Silver (exposition boto3 → fichier texte)
  - job_name: pipeline
    static_configs:
      - targets: ['localhost:9101']
