-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.salarie
(
    employe_id bigint NOT NULL,
    nom_employe character varying NOT NULL,
    prenom_employe character varying NOT NULL,
    date_naissance_employe date NOT NULL,
    departement_id bigint NOT NULL,
    date_embauche date NOT NULL,
    salaire numeric NOT NULL,
    type_contrat_id bigint NOT NULL,
    adresse character varying NOT NULL,
    moyen_deplacement_id bigint NOT NULL,
    nombre_conges bigint NOT NULL,
    PRIMARY KEY (employe_id)
);

COMMENT ON TABLE public.salarie
    IS 'Table correspondant au fichier RH';

CREATE TABLE IF NOT EXISTS public.departement
(
    departement_id bigint NOT NULL,
    nom_departement character varying NOT NULL,
    PRIMARY KEY (departement_id)
);

CREATE TABLE IF NOT EXISTS public.contrat
(
    contrat_id bigint NOT NULL,
    nom_contrat character varying NOT NULL,
    PRIMARY KEY (contrat_id)
);

CREATE TABLE IF NOT EXISTS public.moyen_deplacement
(
    moyen_deplacement_id bigint NOT NULL,
    nom_moyen_deplacement character varying NOT NULL,
    PRIMARY KEY (moyen_deplacement_id)
);

CREATE TABLE IF NOT EXISTS public.pratique_sport
(
    id_evenement_sportif bigint NOT NULL,
    employe_id bigint NOT NULL,
    type_pratique_sportive character varying NOT NULL,
    date timestamp without time zone NOT NULL,
    distance numeric,
    temps_ecoule bigint NOT NULL,
    commentaire text,
    PRIMARY KEY (id_evenement_sportif)
);

CREATE TABLE IF NOT EXISTS public.avantage_salarie
(
    employe_id bigint NOT NULL,
    annee integer NOT NULL,
    eligible_prime_salaire boolean NOT NULL,
    montant_prime numeric NOT NULL,
    eligible_jour_be boolean NOT NULL,
    nb_activite_annee integer NOT NULL,
    avantage_id bigint NOT NULL,
    PRIMARY KEY (avantage_id)
);

ALTER TABLE IF EXISTS public.salarie
    ADD CONSTRAINT cle_departement FOREIGN KEY (departement_id)
    REFERENCES public.departement (departement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salarie
    ADD CONSTRAINT cle_contrat FOREIGN KEY (type_contrat_id)
    REFERENCES public.contrat (contrat_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salarie
    ADD CONSTRAINT cle_moyen_deplacement FOREIGN KEY (moyen_deplacement_id)
    REFERENCES public.moyen_deplacement (moyen_deplacement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pratique_sport
    ADD CONSTRAINT id_employe FOREIGN KEY (employe_id)
    REFERENCES public.salarie (employe_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.avantage_salarie
    ADD CONSTRAINT employe_id FOREIGN KEY (employe_id)
    REFERENCES public.salarie (employe_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;